# Generated by Django 4.2 on 2025-12-15 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detection_type",
                    models.CharField(
                        choices=[("url", "URL"), ("email", "Email")], max_length=10
                    ),
                ),
                ("input_text", models.TextField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("phishing", "Phishing"),
                            ("legitimate", "Legitimate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("features_used", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "detection_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhishingFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=100)),
                ("feature_value", models.FloatField()),
                ("importance", models.FloatField(blank=True, null=True)),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="detection.detectionhistory",
                    ),
                ),
            ],
            options={
                "db_table": "phishing_features",
            },
        ),
    ]
